"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](lines)\
[\ue0c7 [ $os ](bg:background)\ue0c6](background) \
[\ue0c5 ](background)[ $directory](bg:background)\
([\ue0b1 ](background_dark bg:background)[\
$git_branch\
$git_commit\
$git_state\
$git_status\
](bg:background))\
[\ue0b0](background) \
$fill\
( [\ue0c5](background) [ \
$package\
$c\
$cpp\
$cmake\
$deno\
$gleam\
$golang\
$lua\
$nodejs\
$rust\
$typst\
$zig\
$nix_shell\
$meson\
$sudo\
$cmd_duration\
$jobs\
$battery\
[\ue0bc](background)\
](bg:background))\
[─╮](lines) \
$line_break\
[╰─](lines)\
$character\
"""
continuation_prompt = "[➜](lines) "
right_format = "[─╯](lines)"
add_newline = true

palette = 'default'

[palettes.default]
lines = '238'
wheat = '101'
dodgeblue = '27'
skyblue = '117'
golden = '136'
gold = '178'
path = '31'
root = '39'
grey = '244'
orange = '202'
background = '235'
background_dark = '232'

[battery]
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 10
style = "red bold bg:prev_bg"

[[battery.display]]
threshold = 20
style = "orange bold bg:prev_bg"

[bun]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
style = "bold red bg:prev_bg"

[c]
format = "[$symbol($version(-$name))]($style) "
version_format = "${raw}"
symbol = " "
style = "dodgeblue bold bg:prev_bg"

[cpp]
format = "[$symbol($version(-$name))]($style) "
version_format = "${raw}"
symbol = " "
style = "dodgeblue bold bg:prev_bg"

[cmake]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "197 bold bg:prev_bg"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[V](bold green)"
vimcmd_replace_symbol = "[▶](bold green)"
vimcmd_replace_one_symbol = "[▶](bold green)"

[cmd_duration]
format = "[ $duration]($style) "
style = "wheat bg:prev_bg"

[deno]
format = "[$symbol($version)]($style) "
style = "black bold bg:prev_bg"
version_format = "${raw}"

[directory]
format = "[ ](path bg:prev_bg)[$path]($style)[$read_only]($read_only_style) "
style = "root bg:prev_bg"
truncation_length = 3
read_only = " "
read_only_style = "golden bg:prev_bg"
truncate_to_repo = true
before_repo_root_style = "path bg:prev_bg"
repo_root_format = """
[ $before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style) \
"""
repo_root_style = "root bold bg:prev_bg"
fish_style_pwd_dir_length = 2

[fill]
symbol = "─"
style = "lines"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold green bg:background"
only_attached = true

[git_commit]
format = "[ ]($style)@[$hash]($style) "
commit_hash_length = 6
only_detached = true
style = "green bold bg:prev_bg"

[git_state]
style = "bold yellow bg:prev_bg"

[git_status]
format = "([$ahead_behind](green bg:prev_bg)$all_status )"
conflicted = "[~$count](red bg:prev_bg)"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "[?$count](39 bg:prev_bg)"
stashed = "[*$count](green bg:prev_bg)"
modified = "[!$count](gold bg:prev_bg)"
staged = "[+$count](gold bg:prev_bg)"
renamed = "[»$count](gold bg:prev_bg)"
deleted = "[✘$count](gold bg:prev_bg)"
ignore_submodules = true

[gleam]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "177 bold bg:prev_bg"

[golang]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "skyblue bold bg:prev_bg"

[jobs]
format = "[$symbol$number]($style) "
symbol = " "
style = "bold blue bg:prev_bg"

[lua]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "dodgeblue bold bg:prev_bg"

[meson]
format = "[$symbol$project]($style) "
symbol = "⬢ "
style = "91 bold bg:prev_bg"


[nix_shell]
format = "[$symbol$state]($style) "
symbol = "󱄅 "
style = "dodgeblue bold bg:prev_bg"

[nodejs]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "green bold bg:prev_bg"

[os]
disabled = false
style = "white bold bg:prev_bg"

[os.symbols]
Alpine = " "
Amazon = "󰆧 "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Solus = " "
Ubuntu = " "
Windows = " "

[package]
format = "[$symbol$version]($style) "
version_format = "${raw}"
style = "208 bold bg:prev_bg"

[python]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "yellow bold bg:prev_bg"

[rust]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "orange bold bg:prev_bg"

[sudo]
format = "[$symbol]($style) "
symbol = " "
style = "yellow bold bg:prev_bg"
disabled = false

[typst]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "#0093A7 bold bg:prev_bg"

[zig]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = " "
style = "yellow bold bg:prev_bg"
