theme = 'tokyonight'
#
# The editor files will be opened with. (Leave blank to use the EDITOR environment variable).
editor = ""
# The editor directories will be opened with. (Leave blank to use the default editors).
dir_editor = "nvim"
auto_check_update = true
cd_on_quit = false
default_open_file_preview = false
show_image_preview = true

show_panel_footer_info = true
default_directory = "."
# Display file sizes using powers of 1000 (kB, MB, GB) instead of powers of 1024 (KiB, MiB, GiB).
file_size_use_si = false
# Default sort type (0: Name, 1: Size, 2: Date Modified, 3: Type).
default_sort_type = 0
# Default sort order (false: Ascending, true: Descending).
sort_order_reversed = false
# Case sensitive sort by name (upper "B" comes before lower "a" if true).
case_sensitive_sort = false
shell_close_on_success = false
debug = false
ignore_missing_fields = false
#
# ================   Style =================
#
code_previewer = 'bat'
nerdfont = true
transparent_background = false
# File preview width allow '0' (this mean same as file panel),'x' x must be from 2 to 10 (This means that the width of the file preview will be one xth of the total width.)
file_preview_width = 0
# The length of the sidebar. If you don't want to display the sidebar, you can input 0 directly. If you want to display the value, please place it in the range of 3-20.
sidebar_width = 20

# Border style
border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'
#
# ========== PLUGINS ========== #
#
metadata = true
enable_md5_checksum = false
zoxide_support = false
